# -*- coding: utf-8 -*-
"""Validity_using_Regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OK_FfADk56PaRYcU7h1d8FYQIbwMm1iT
"""

import re

#starts with letters from A-Z, a-z, 0-9 with atleast one or more occurences
regex_email = "[A-Za-z0-9]+[.]?[0-9a-zA-z]+@gmail\.com"
regex_num= "\+880[0-9]{10}"

emails = []
numbers = []
f1 = open("emails.txt", "w")
f2 = open("contact_numbers.txt", "w")
f = open("demofile.txt")
for x in f:
  emails.append(re.findall(regex_email, x))
  numbers.append(re.findall(regex_num, x))
for email in emails:
    f1.writelines(email)
    f1.write("\n")
for number in numbers:
    f2.writelines(number)
    f2.write("\n")
f1.close()
f2.close()